Repository Netcracker/qubership-dbaas-client, pull requests merged in 2025-09, with the labels that each got.

#50 chore(deps): update dependency org.springframework:spring-webmvc to v6.2.10 [security]
  dbaas-client-java/dbaas-client-sample-tests/cassandra-sample-test/pom.xml
  dbaas-client-java/dbaas-client-sample-tests/mongo-sample-test/pom.xml
  dbaas-client-java/dbaas-client-sample-tests/postgres-sample-test/pom.xml
Labels: type:patch, branch:main, renovate:core

#40 chore(deps): update dependency org.hibernate:hibernate-core to v6.6.26.final
  dbaas-client-java/dbaas-client-sample-tests/postgres-sample-test/pom.xml
Labels: renovate, type:patch

#39 chore(deps): update dependency io.micrometer:micrometer-core to v1.14.9
  dbaas-client-bom-parent/dbaas-client-bom-internal/pom.xml
Labels: renovate, type:patch

#83 chore(deps): replace maven with org.hibernate.orm:hibernate-processor 7.1.1.final
  dbaas-client-java/dbaas-client-postgres-starter/pom.xml
  dbaas-client-java/dbaas-client-sample-tests/postgres-sample-test/pom.xml
Labels: bug, branch:main, renovate:core, manager:maven, group:maven

#80 chore(deps): update netcracker/qubership-core-infra action to v1.0.9
  .github/workflows/maven-build.yaml
Labels: type:patch, branch:main, renovate:core, manager:github-actions
